### ISSUE TITLE
Unable to install bloom on Ubuntu

### ISSUE THREAD

**Issue by srkgupta** [valeriansaliou/bloom#1]
I am following the steps mentioned here to install Bloom on Ubuntu 16.04.3:
https://crates.io/crates/bloom-server

But I see the following error:

W: The repository 'https://packagecloud.io/valeriansaliou/bloom/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by valeriansaliou** [comment]
Hi! Try using the Debian package, it should work just fine. For now our packaging is only Debian 8 x32

**Comment by srkgupta** [comment]
The Debian packages are all compiled in i386, whereas my server is on amd64. Hence when I try to install the debian package, I see this error:

dpkg: error processing archive bloom_1.8.deb (--install):
 package architecture (i386) does not match system (amd64)

Are there any debian packages compiled with 64-bit processors ?

**Comment by valeriansaliou** [comment]
Hi! Not yet, it's a bit tedious for me to cross-compile 32 bits and 64 bits on the same machine unfortunately.
