### ISSUE TITLE
Panicked at 'could not spawn redis pool'

### ISSUE THREAD

**Issue by andersonsantos** [valeriansaliou/bloom#10]
Hi there @valeriansaliou :)
I just updated Bloom with the lastest cargo package (before I had it compiled from source) and now I'm getting this error:

`
root@api02:~/www/api# RUST_BACKTRACE=1 /root/.cargo/bin/bloom -c /etc/bloom.cfg
thread 'main' panicked at 'could not spawn redis pool', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bloom-server-1.26.0/src/cache/store.rs:97:31
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:215
             at src/libstd/panicking.rs:478
   3: std::panicking::begin_panic
   4: std::sync::once::Once::call_once::{{closure}}
   5: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:387
   6: <bloom::APP_CACHE_STORE as core::ops::deref::Deref>::deref
   7: bloom::main
   8: std::rt::lang_start::{{closure}}
   9: main
  10: __libc_start_main
  11: _start
`
Do you have any idea of why?
I had 2 servers with bloom installed from the source, the one I didn't update is still working, the other one isn't. Also, I created a third server and made a clean install from cargo, and got the same error.

Thanks

**Comment by valeriansaliou** [comment]
Hello there!

Can you share more details on the timing after which the error shows? I've compiled Bloom latest from master with Rust nightly 1.35, and not seeing that error.

**Comment by andersonsantos** [comment]
Hi!
Just tried to compile from source with rust 1.35 also, and still getting this error.
It happens just after I try to launch it with:
/root/tools/bloom/target/release/bloom -c /etc/bloom.cfg
Also tried with the cargo package and the Ubuntu repo package.
I even tried to create a new Redis server on Google Cloud Memorystore and tried again... this time I'm really lost.

Cargo version:
cargo 1.35.0 (6f3e9c367 2019-04-04)
Rust:
rustc 1.35.0 (3c235d560 2019-05-20)

My bloom.cfg file is the same as before when it was working:

# Bloom
# HTTP REST API caching middleware
# Configuration file
# Example: https://github.com/valeriansaliou/bloom/blob/master/config.cfg


[server]

log_level = "error"
inet = "0.0.0.0:5555"


[control]

inet = "0.0.0.0:6666"
tcp_timeout = 300


[proxy]

[[proxy.shard]]

shard = 0
host = "127.0.0.1"
port = 4000


[cache]

ttl_default = 2
executor_pool = 1024

disable_read = false
disable_write = false

compress_body = true


[redis]

host = "10.0.0.4"
port = 6379

database = 1

pool_size = 600
max_lifetime_seconds = 60
idle_timeout_seconds = 600
connection_timeout_seconds = 1

max_key_size = 256000
max_key_expiration = 2592000

**Comment by andersonsantos** [comment]
By the way... posted Bloom at Hackernews today and it made to the front page:
![image](https://user-images.githubusercontent.com/113621/58964332-17ba5b80-8785-11e9-9b39-e8eeea7854e1.png)
https://news.ycombinator.com/

**Comment by valeriansaliou** [comment]
Wow, thanks for HN!

On your issue, let's gather some logs. Can you pull the Git master of Bloom on your computer, and edit the following file locally: https://github.com/valeriansaliou/bloom/blob/master/src/cache/store.rs#L91

Replacing the portion highlighted with:

```rust
                match builder.build(manager) {
                    Ok(pool) => {
                        info!("bound to store backend");

                        CacheStore { pool: pool }
                    }
                    Err(err) => panic!("could not spawn redis pool: {}", err),
                }
```

Then, cargo build it as normal, and run it. You'll get error details in the panic.

**Comment by andersonsantos** [comment]
@valeriansaliou after your suggestion, I got a timeout connection error... I changed connection_timeout_seconds from 1 to 2 and everything worked out fine!
2 days ago Google Cloud had errors on their Google Cloud Networking services...my problem started yesterday... so I guess that in fixing the GCN problem they added some latency in the internal network.

Thank you for your support as always!
