### ISSUE TITLE
Metrics support

### ISSUE THREAD

**Issue by ryudice** [valeriansaliou/bloom#3]
Add support to send metrics to influxdb

**Comment by valeriansaliou** [comment]
I'm open to PR on this!

BTW may I know how / for which purpose you're using Bloom? The project has been recently launched (though already running stable and successfully in production at scale at Crisp!) and I'm probing the community use / need for Bloom.

Probably we'll need a generic plugin system on Bloom to be able to extract data and inject live configuration changes (an I/O interface). On which, we may integrate a wide range of stuff without needing to touch the Bloom core (eg. influxdb).

**Comment by valeriansaliou** [comment]
Closing this and moving it to #4.
